baseurl: "/"
languageCode: en-us
title: ALLcology Lab
theme: blackburn
author: Travis M. Thomas
copyright: '&copy; 2022. All rights reserved.'
canonifyurls: yes
paginate: 10
ignoreFiles: = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

indexes:
  tag: tags
  topic: topics
params:
  brand: ALLcology
  dateFormat: 02 Jan 2006, 15:04
  disqus: Your Disqus shortname
  googleAnalytics: Your Google Analytics tracking ID
  highlightjs: androidstudio
  subtitle: UF / Nature Coast Biological Station
                
menu:
  main:
    - identifier: home
      name: Home
      pre: <i class='fa fa-home fa-fw'></i>
      url: /home/
      weight: 10
    - identifier: projects
      name: Projects
      pre: <i class='fa fa-list fa-fw'></i>
      url: /post/
      weight: 20
    - identifier: about
      name: About
      pre: <i class='fa fa-list fa-fw'></i>
      url: /about/
      weight: 30
    - identifier: team
      name: Team
      pre: <i class='fa fa-user fa-fw'></i>
      url: /team/
      weight: 40
    
social:
  facebook: '*'
  github: Tatort
  instagram: '*'
  twitter: '*'

markup:
  goldmark:
    renderer:
      unsafe: true
